base_url = "https://yakshi.uno"

compile_sass = true
generate_robots_txt = true
generate_feeds = true

theme = "duckquill"
title = "Uno Yakshi"
description = "Uno Yakshi's personal web-site"

taxonomies = [
    { name = "tags"},
    { name = "categories"},
]

[markdown]
extra_syntaxes_and_themes = [
    "highlight_themes",
]

highlight_code = true
highlight_theme = "Darkula"
render_emoji = true
smart_punctuation = true

[search]
include_title = true
include_date = true
include_path = true
include_content = true
include_description = true

[extra]
hard_breaks = true
default_theme = "dark"
apple_touch_icon = "apple-touch-icon.png"
favicon = "favicon.png"
accent_color = "#dedede"
accent_color_dark = "#808080"
lang = "en"
codeblock = true
show_copy_button = true
katex = true
toc = true
toc_sidebar = true

styles = [
    "mods.css",
    "tufte.css",
]

[extra.nav]
links = [
    { url = "/about", name = "About" },
    { url = "/blog", name = "Blog" },
    { url = "/WHS_CV.pdf", name = "CV" },
]
