# The URL the site will be built for
base_url = "https://yakshi.uno"

compile_sass = true
build_search_index = true
generate_robots_txt = true
generate_feeds = true

theme = "duckquill"
title = "UnoYakshi"
description = "This is our home now"

[markdown]
extra_syntaxes_and_themes = [
    "highlight_themes",
]

highlight_code = true
highlight_theme = "Darkula"
render_emoji = true
smart_punctuation = true

[search]
include_title = true
include_date = true
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# Whether to include the description of the page/section in the index
include_description = true

[extra]
default_theme = "dark"
lang = "en"
toc = true
toc_sidebar = true

styles = [
    "mods.css",
]

[extra.nav]
links = [
    { url = "/", name = "Home" },
    { url = "/about", name = "About" },
    { url = "/blog", name = "Blog" }
]
